import { task } from "hardhat/config"

task("KeyringGateway:deploy", "deploy Keyring Gateway").setAction(async (taskArgs, { ethers, upgrades }) => {
  const [signer] = await ethers.getSigners()
  const KeyringGateway = await ethers.getContractFactory("KeyringGateway")
  const keyringGateway = await upgrades.deployProxy(KeyringGateway, [signer.address])
  await keyringGateway.waitForDeployment()
  console.log("KeyringGateway deployed to:", await keyringGateway.getAddress())
})

task("KeyringSafeModule:deploy", "deploy Keyring Gateway")
  .addParam("gateway", "Keyring Gateway")
  .addParam("safe", "The safe to which this module is attached")
  .addParam("signer", "The address associated to the shared public key generated by the keyring network")
  .setAction(async (taskArgs, { ethers, upgrades }) => {
    const [signer] = await ethers.getSigners()
    const KeyringSafeModule = await ethers.getContractFactory("KeyringSafeModule")
    const keyringSafeModule = await upgrades.deployProxy(KeyringSafeModule, [
      signer.address,
      taskArgs.gateway,
      taskArgs.safe,
      taskArgs.signer,
    ])
    await keyringSafeModule.waitForDeployment()
    console.log("KeyringSafeModule deployed to:", await keyringSafeModule.getAddress())
  })
